### PR TITLE
Support for multiprocessed fastq output

### LINKED ISSUE #3: Multi-thread fastq read/write operations
Currently, reading the input fastq file and writing the output demuxed files are single-threaded. It can be sped up by multi-threading.

### PR DESCRIPTION
**Pull request by remiolsen**
closes #3

Parallelise per fastq file output (and not fastq file entries chunks). I will not explain further.

Needs some testing. Setting this as draft PR

### CODE REVIEW

**Comment by remiolsen** [comment]
Also updated to ruff 0.3.0 for ruff-precommit, since it was fighting with GH action's version of ruff.

**Comment by remiolsen** [comment]
I changed my mind. I might as well try to parallise lenient mode while I'm at it.

**Comment by remiolsen** [comment]
closes #50

I'm satisfied that my multiprocessing.spawn usage works on OSX and Linux (Miarka). Hopefully it will not cause Windows to explode and catch fire. 

Ready for review now @alneberg

**Review by alneberg — APPROVED** [review]
Looks good, and runs fine both on the m2 macbook and linux server.

**Pull request merged**
